<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="Klant" Id="{83c63601-1ba3-4a51-a444-c63301a380d8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Klant
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Klant">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>