<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="kleurmachine" Id="{e2f2c538-0dc9-411e-a330-8428cfac9392}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM kleurmachine
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="kleurmachine">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>