<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN" Id="{37e4aa0d-7777-400c-a8ca-388435fd5c5b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	counter : INT := 0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[counter := counter + 1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>