<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="Medewerker" Id="{37e4aa0d-7777-400c-a8ca-388435fd5c5b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Medewerker
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Medewerker">
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>